export PS1='$HOSTNAME (${PWD##*/}) | '
alias k='vim ~/.kshrc'
alias w='wget'
alias s='sam -d'
alias c='cd'
alias v='vim'
alias 2.='cd ..'
alias 4.='cd .. && cd ..'
alias av='cd /var/www/werc/sites/avsbq.org'
alias blog='cd /var/www/werc/sites/avsbq.org/blog'
alias etc='cd /etc'
alias arc='cd /var/www/werc/sites/archive.avsbq.org'
alias mis='cd /var/www/werc/sites/archive.avsbq.org/misc'
alias per='cd /var/www/werc/sites/archive.avsbq.org/misc/personal'
alias fun='cd /var/www/werc/sites/archive.avsbq.org/misc/personal/funny'
alias alev='cd /var/www/werc/sites/archive.avsbq.org/misc/personal/school/a_level'
alias mal='cd /var/www/werc/sites/mal.avsbq.org'
alias tut='cd /var/www/werc/sites/tutorial.avsbq.org'
alias proj='cd /var/www/werc/sites/project.avsbq.org'
alias ico='cd /var/www/werc/sites/iconography.avsbq.org'
alias lan='cd /var/www/werc/sites/language.avsbq.org'
alias pro='cd /var/www/werc/sites/profile.avsbq.org'
alias en='cd /var/www/werc/sites/language.avsbq.org/english'
alias enw='vim /var/www/werc/sites/language.avsbq.org/english/words.md'
alias enp='cd /var/www/werc/sites/language.avsbq.org/english/phrases'
alias cn='cd /var/www/werc/sites/language.avsbq.org/chinese'
alias jp='cd /var/www/werc/sites/language.avsbq.org/japanese'
alias bn='cd /var/www/werc/sites/language.avsbq.org/bengali'
alias oen='cd /var/www/werc/sites/language.avsbq.org/old_english'

# ARIF ALIAS

alias par='cd /var/www/werc/sites/pariffin.org'

