    <div>
      <a href="https://avsbq.org"><div class="square"></div></a>
      <a href="https://archive.avsbq.org">arcarchive</a> -
      <a href="https://mal.avsbq.org">mal</a> -
      <a href="https://language.avsbq.org">languages</a> -
      <a href="https://link.avsbq.org">links</a> -
      <a href="https://iconography.avsbq.org">liturgical arts</a> -
      <a href="https://project.avsbq.org">projects</a> -
      <a href="https://tutorial.avsbq.org">tutorials</a> 
    </div>

    <div>
      <a href="https://profile.avsbq.org/"><i>profile</i></a> |
      <a href="https://avsbq.org/.videos">vids</a> -
      <a href="https://avsbq.org/.webring">webring</a>
    </div>

